--- #YAML:1.0
name:                Data-UUID-Base64URLSafe
version:             0.33
abstract:            URL-safe UUIDs
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Data::UUID:                    0
    MIME::Base64::URLSafe:         0
    Test::More:                    0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
